##
## Dockerfile for NEST v. 2.16.0
## Documentation: http://www.nest-simulator.org/installation/
##

FROM volr/docker-nest-2.16.0:latest

ENV PATH="${PATH}:/nest-${VERSION}/bin/:/nest-${VERSION}/lib"
ENV PYTHONPATH="/nest-${VERSION}/lib/python2.7/site-packages/"
ENV PYTHONIOENCODING="utf8"

RUN pip3 install --no-binary :all: PyNN
RUN pip3 install mpi4py numpy scipy matplotlib addict future lazyarray neo pytest

# Install volrpynn
ADD . /volrpynn
RUN pip3 install -e /volrpynn

# Prepare working environment
RUN mkdir /data
WORKDIR /root
VOLUME ["/data"]

CMD ["python"]
